name = "go-dip-sh"
main = "src/worker.ts"
compatibility_date = "2025-09-23"
workers_dev = true
tsconfig = "tsconfig.json"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "LINKS"
id = "56262969012745d1aad0e51fa75c773a"
preview_id = "9e6e1c09c4be4f84b75064c3f642bee4"
