name: Deploy Worker and Release CLI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-worker:
    name: Deploy Cloudflare Worker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --no-progress

      - name: Deploy via Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: bunx wrangler deploy

  build-cli:
    name: Build CLI (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --no-progress

      - name: Build binary
        shell: bash
        run: |
          set -euo pipefail
          OUT=shorten
          SUF="linux-x64"
          if [ "${{ matrix.os }}" = "macos-latest" ]; then SUF="macos-x64"; fi
          if [ "${{ matrix.os }}" = "windows-latest" ]; then SUF="windows-x64"; OUT="shorten.exe"; fi
          bun run build
          mv "$OUT" "shorten-${SUF}${OUT#shorten}"
          echo "ARTIFACT=shorten-${SUF}${OUT#shorten}" >> "$GITHUB_ENV"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}

  release-cli:
    name: Create GitHub Release
    needs: build-cli
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: shorten-*
          merge-multiple: true

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cli-${{ github.sha }}
          name: CLI ${{ github.sha }}
          body: |
            CLI binaries built from ${{ github.sha }}.
            Includes Linux, macOS, and Windows builds compiled via Bun.
          files: |
            shorten-*
